<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Commands\" />
    <Folder Include="Data\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cpaciente.Sdk\Cpaciente.Sdk.csproj" />
  </ItemGroup>

</Project>
